project:
  type: website
  output-dir: docs

website:
  title: "Sowdhamini's Page"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Skills & Projects.qmd
      

format:
  html:
    theme: costo
    css: styles.css
    toc: true

editor: visual

